### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by poke1024** [scikit-geometry/scikit-geometry#23]
This looks like a memory leak to me:

https://github.com/scikit-geometry/scikit-geometry/blob/1cedc353b44d61b98e42666361f704d5cdd6bea6/src/polygon.cpp#L26

Shouldn't this be something along the lines of

```
py::class_<Polygon_2, std::shared_ptr<Polygon_2>>(m, "Polygon")
.def(py::init([](const std::vector<Point_2>& vertices) {
    return std::make_shared<Polygon_2>(vertices.begin(), vertices.end()); 
}))
```

Or am I missing something here?

**Comment by wolfv** [comment]
hmmm ... i wonder if we could just remove the `new`.
In general, I think that pybind11 is smart enough to detect that it's a raw pointer and call delete when the Python object is garbage collected.

https://pybind11.readthedocs.io/en/stable/advanced/functions.html#return-value-policies

**Comment by poke1024** [comment]
Probably you're right, it probably falls back to `return_value_policy::take_ownership`. I'll do a quick check if this really happens. But it should according to the docs.
