### ISSUE TITLE
How to contribute additional features

### ISSUE THREAD

**Issue by dmontagu** [scikit-geometry/scikit-geometry#40]
Here is a gist with a variety of functionality I would love to merge into a more broadly supported package:

https://gist.github.com/dmontagu/ea9f7e60e83fc8693245d9e1ddcc31aa

(Note: though I have tried my best to follow the style/conventions in the CGAL examples and idiomatic C++, I am a much more confident of python programmer than C++ programmer and my C++ may well be non-idiomatic or unsafe. But I'm happy to rewrite things as desired with a little guidance!)

In particular, it has some functionality related to:

1. constrained delaunay triangulation
2. SurfaceMeshShortestPath (just for the convenient AABB tree API, in that gist anyway)
3. Extracting subsets of a mesh based on a provided halfedge boundary

(I was trying to use this functionality to produce a fast exact-timezone-lookup package, which is why it refers to namespace `cgal_tz`, but I have since found better approaches for that specific problem. But I have frequently wanted to make use of these capabilities elsewhere.)

I could also quickly throw together bindings for the actual geodesic queries using SurfaceMeshShortestPath, though they are not included in that gist.

------

It's not clear to me to what extent this functionality is compatible with / of interest to this package, or what it would look like to merge it. (Clearly it would require substantial clean-up/refactors first, but I'd be happy to do that given some direction about what changes might make it desirable to merge.)

If you are interested in incorporating some/all of this functionality, I also think it might make sense to smart small (e.g., with *just* the constrained delaunay triangulation support) and go from there.

Before I throw together a proper pull request though, I was hoping to get some bird's-eye-view feedback so I don't waste too much time on things that are likely to be rejected.

------

Some concrete questions:
* Would you be interested in adding support for constrained delaunay triangulations?
* Would you be interested in adding support for SurfaceMesh / SurfaceMeshShortestPaths?
* Do you have any strong opinions about what the python API should look like for those modules? More generally, are there any "principles" that you'd like to follow that would be good to be aware of?
* How do you feel about adding functionality that extends what is currently available in CGAL, as opposed to being just a pythonic wrapper? (For example, the `sector` function I added to `Mesh` that takes a mesh and a collection of halfedges, and returns the submesh bounded by those halfedges. As far as I'm aware, such functionality isn't baked into CGAL, but I have frequently found it useful.)

**Comment by wolfv** [comment]
Hi @dmontagu thanks for opening this issue! 

I think yes, all of the functionality you have listed would be a great fit for this library. Especially constrained delaunay triangulation -- I have also already played with it. 
Regarding the API, I have so far tried to just "pythonize" what's in CGAL itself. 
However, especially the Delaunay part that is alrady in scikit-geometry might need some rework at some point. If you want to take a stab at this (and add constrained triangulation), that would be incredibly welcome! 

Also, SurfaceMesh, SurfaceMeshClosestPath sound like good additions.

I think extending CGAL in ways that is useful is fine.

If you want to start with Delaunay + Constrained Delaunay, that would be awesome and I am very happy to review a PR. Maybe your idea with the triangulator class is actually better than my wrapping of the CGAL classes... 

Let me know if this enough motivation / information for you to start a PR?

**Comment by Michael-fore** [comment]
Besides what is listen above, Is there a TODO list somewhere? I have been reading through the repository and would love to help out if i can.
