### ISSUE TITLE
Request for inserting multiple line segments at once

### ISSUE THREAD

**Issue by eboix** [scikit-geometry/scikit-geometry#49]
Hi @wolfv,
Thank you for your amazing work!

I was wondering if you could add a wrapper for inserting a list of segments into an arrangement. 

It would suffice to add the following lines to `src/arrangement.cpp`:

```
void insert_segments_in_arr(Segment_Arrangement_2& arr, std::vector<Segment_2>& segs) {
    CGAL::insert(arr, segs.begin(), segs.end());
}
```

And then add the following method to the `Arrangement` pybind class:
```
.def("insert_segments", &insert_segments_in_arr)
```

On my machine, this can be orders of magnitude faster than adding segments one at a time with the `insert` method.

I could write a push request if it's easier for you.

**Comment by wolfv** [comment]
Hi @eboix 

I am more than happy to accept a pull request implementing this feature.
