### ISSUE TITLE
Thanks + Robot demo. 

### ISSUE THREAD

**Issue by srush** [scikit-geometry/scikit-geometry#66]
This is not an issue but I thought I would say thank you for the awesome library. 

Just for fun I was doing this this navigation challenge the other day in python ( https://icfpcontest2019.github.io/ ) and I realized I needed a good computational geometry library to handle line-of-sight, contour based polygons, graphing, intersection, and nearest point heuristics. I was able to find your library and figure most of this stuff out really quickly thanks to your docs. 

Here's what the little bot looks like walking around cleaning. Red squares are a polygon set, green is a polygon, the tetris piece can cover only in line-of-sight, and the purples are extenders (it goes for them first). It grows with immutable polygon union, eats with difference, distance, perimeter and bbox's are used as a heuristic (the search is not so good, I got lazy). 

![image](https://github.com/srush/temp/raw/master/movie.gif)

The only thing I couldn't figure out how to do with the library is polygon transposition, rotation around a point, union without first knowing if polygons intersect, and fast checking if a point is in a polygon with a hole (I check outer and the inner ones, is that right?). 

Thanks again.

**Comment by wolfv** [comment]
hey @srush thanks for showing the demo! Really enjoyed it and I am happy it's useful!

Did you figure out how to do the translation / rotation stuff? There are some functions to do that for primitives, but I am not sure if they are also implemetned for polygons. You could iterate over the vertices of teh polygon and handle each primitive seperately though.
