### ISSUE TITLE
Nested offset_polygons increasing execution time for every iteration

### ISSUE THREAD

**Issue by Tristan10** [scikit-geometry/scikit-geometry#78]
I am trying to get all "inner" polygons of a given polygon by shrinking it by a constant value. Every iteration to calculate the next offset polygon takes noticeably longer than the one before. Here is my code for reference:

```
poly = Polygon(polypoints)
skel = skeleton.create_interior_straight_skeleton(poly)

offset_polys = skel.offset_polygons(10)

while len(offset_polys) > 0:
        offset_poly = offset_polys[0]

        # PROCESS THE POLYGON

        offset_polys = skeleton.create_interior_straight_skeleton(offset_poly).offset_polygons(10)

        print('Calculated next largest polygon.')
```

Is there a reason why calculating the offset polygons in quick succession like this is slowing down?

**Comment by Tristan10** [comment]
For example, here's the time it took to generate the first offset, followed by the next 5 smaller polygons.

> Took 0.03400707244873047 seconds (0.0005667845408121745 mins) to calculate offset polygon.
> 
> Took 0.04300951957702637 seconds (0.0007168253262837728 mins) to calculate offset polygon.
> 
> Took 0.10302305221557617 seconds (0.0017170508702596028 mins) to calculate offset polygon.
> 
> Took 0.622647762298584 seconds (0.010377462704976399 mins) to calculate offset polygon.
> 
> Took 4.497013568878174 seconds (0.07495022614796956 mins) to calculate offset polygon.
> 
> Took 33.39146637916565 seconds (0.5565244396527608 mins) to calculate offset polygon.

**Comment by Tristan10** [comment]
Got a little ahead of myself. As the CGAL docs say

> You can reuse the same skeleton to generate offsets at a different distance, which is recommended because producing the straight skeleton is much slower than generating offset polygons.

I solved my issue by using one skeleton instance and incrementing my offset distance.

**Comment by wolfv** [comment]
great! If you want, you could send a PR to the docs.
