### ISSUE TITLE
incorrect build_ext c opts and do_intersect Segment_3 Segment_3 also fails on macOS

### ISSUE THREAD

**Issue by silicontrip** [scikit-geometry/scikit-geometry#92]
I'm attempting to install from source but I've encountered a number of build issues.
setup.py can find the CGAL libraries but does not pass the include path or library path to clang in the build_ext module.   I  modified setup.py to pass the needed directories.

```
class BuildExt(build_ext):
    """A custom build extension for adding compiler-specific options."""
    c_opts = {
        'msvc': ['/EHsc', '/std:c++14'],
        'unix': ['-I/usr/local/include'],
    }
    l_opts = {
        'msvc': [],
        'unix': ['-L/usr/local/lib'],
    }
```

It compiles a number of files but then gives an error saying that a call to do_intersect is ambiguous.
```
In file included from src/kernel.cpp:1:
In file included from ./include/skgeom.hpp:2:
In file included from /usr/local/include/CGAL/Exact_predicates_exact_constructions_kernel.h:20:
In file included from /usr/local/include/CGAL/Simple_cartesian.h:20:
In file included from /usr/local/include/CGAL/Cartesian/Cartesian_base.h:62:
In file included from /usr/local/include/CGAL/Cartesian/function_objects.h:20:
In file included from /usr/local/include/CGAL/Kernel/function_objects.h:29:
In file included from /usr/local/include/CGAL/intersection_3.h:74:
In file included from /usr/local/include/CGAL/Intersections_3/Segment_3_Segment_3.h:24:
/usr/local/include/CGAL/Intersections_3/internal/Segment_3_Segment_3_do_intersect.h:33:12: error: call to 'do_intersect' is ambiguous
```
Looking in the kernel.cpp I see a few comments saying `<-- THIS ONE ERRORS ON OS-X, windows (VS) & linux work fine`
So I've also commented out `m.def("do_intersect", &do_intersect<Segment_3, Segment_3>) `

It builds at this point, but I'm not sure if it will test correctly.
If this is not the correct way to fix the issues, let me know what the correct fix is.

Thank you
Mark

**Comment by jskrzypek** [comment]
@silicontrip Thanks for the pointers! I will add these fixes to my PR #88
